{% set name = "nsbm" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fvalle1/trisbm/archive/refs/tags/{{ version }}.tar.gz
  sha256: f9184dda34cfb78387614e17a567d9ae3cc1c2250a38bd64724affbb437566c6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pandas
    - cloudpickle
    - graph-tool

test:
  requires:
    - python {{ python_min }}
  imports:
    - trisbm
  source_files:
    - tests
  commands:
    - python -c "from nsbm import nsbm; model=nsbm()"
    - python tests/run_tests.py

about:
  home: https://github.com/BioPhys-Turin/nsbm
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: nSBM, keyword informed topic modeling
  description: |
    Package to run n-partite Stocastich Block Modeling.
  doc_url: https://fvalle1.github.io/nsbm/
  dev_url: https://github.com/fvalle1/nsbm

extra:
  recipe-maintainers:
    - fvalle1
